# Generated by Django 5.2.6 on 2025-09-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_tenantgroup_unique_together_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantuserprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='tenantuserprofile',
            name='role',
            field=models.ManyToManyField(blank=True, to='groups.tenantgroup'),
        ),
    ]
