# Generated by Django 5.2.6 on 2025-09-26 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_tenantuserprofile_role_tenantuserprofile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenantuserprofile',
            old_name='role',
            new_name='groups',
        ),
    ]
