# Generated by Django 5.2.6 on 2025-09-26 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tenantgroup',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tenantgroup',
            name='tenant',
        ),
    ]
